//Model Data
//used in
var markers = [];
var userLocation;
var userMarker;
var markerList = [];

//Takes results from Google Text search and creates markers and marker arrays
function gymMarkers(results){
	for (var i = 0; i < results.length; i++) {
		var marker = new google.maps.Marker({
			map: map,
			position: results[i].geometry.location,
			title: results[i].name,
			address: results[i].formatted_address
		});
		markers.push(marker);
		marker.addListener('click', function() {
        	createInfoWindow(this, largeInfowindow);
      	});
    }

    ko.applyBindings(new ViewModel());

};

var Marker = function(data) {
	this.markerData = data
	this.position = data.position;
	this.title = ko.observable(data.title);
	this.address = ko.observable(data.address);
	this.belowDistance = ko.observable(true)
};

var ViewModel = function() {
	var self = this;

	markers.forEach(function(markerItem){
		markerList.push( new Marker(markerItem) );
	});

	console.log(markerList[2].address())

	this.changeCurrentMarker = function(data){
		console.dir(data.name)
		self.currentMarker(data)
	};

	this.currentMarker = ko.observable();

};



	function createInfoWindow(clickedmarker, infowindow){
		var inforWindowContent = "<div><b>" + clickedmarker.title + "</b></div><br><div>" + clickedmarker.address + "</div>"
		if (infowindow.marker != clickedmarker) {
			infowindow.marker = clickedmarker;
			infowindow.setContent(inforWindowContent);
			infowindow.open(map, clickedmarker);

		};
	};

	/*function createListings(markers) {
		$('#list').empty();
		for (var i = 0; i < markers.length; i++) {
			var listingsContent = "<div><h3>" + filteredMarkers[i].title + "</h3>" + filteredMarkers[i].address + "</div><hr>";
			$('#list').append(listingsContent);
		}
	};*/

    function hideMarkers(markerList) {
        for (var i = 0; i < markerList.length; i++) {
          markerList[i].setMap(null);
        }
    };

     function setMarkers(markerList) {
        console.log(markerList);
        for (var i = 0; i < markerList.length; i++) {
          markerList[i].setMap(map);
        }
    };

    //function takes in a userLocation that is input by the user and determines distances from all marker locations
    //calls function filterByDistance()
	function withinDistance() {
    	var service = new google.maps.DistanceMatrixService();
		var userLocation = document.getElementById('location').value;
		if (userLocation == ""){
			window.alert('A starting location is required.')
		} else{
			hideMarkers(markers);
			userLocationMarker(userLocation);
			var gymDestinations = [];
			for (var i = 0; i < markers.length; i++){
				gymDestinations.push(markers[i].address)
			}
		console.log(userLocation)

		service.getDistanceMatrix({
	    	origins: [userLocation],
	    	destinations: gymDestinations,
	    	unitSystem: google.maps.UnitSystem.IMPERIAL,
	    	travelMode: 'WALKING',
	  	}, function(response, status) {
            if (status !== google.maps.DistanceMatrixStatus.OK) {
              window.alert('Error was: ' + status);
            } else {
              	filterByDistance(response);
            }
          });
        }
    }

    //takes in data generated by withinDistance() and determines if marker location is within the distance of location chosen by user
    //and creates new array data in filteredMarkers of locations that are within that distance
    function filterByDistance(response){
		var withinDistance = document.getElementById('max-miles').value;
		var results = response.rows[0].elements;
		console.log(results);
		for (var i = 0; i < results.length; i++) {
			var meters = results[i].distance.value;
			var miles = metersToMiles(meters);
			if (miles >= withinDistance) {
				markerList[i].belowDistance(false);
				console.log(markerList)

			}
			else {
				markerList[i].belowDistance(true);
			}
		}
		//setMarkers(filteredMarkers);
		//createListings(filteredMarkers);
	};

    function userLocationMarker(userLocation){
    	geocoder = new google.maps.Geocoder();
    	geocoder.geocode({'address': userLocation}, function(results, status) {
          if (status === 'OK') {
          	if (userMarker !== undefined){ //if current userMarker, resets position
          		console.log(userMarker);
    			userMarker.setPosition(results[0].geometry.location);
       		}
    		else{  //if no current userMarker, creates userMarker
    		userMarker = new google.maps.Marker({
				map: map,
				position: results[0].geometry.location,
				title: "Your Location",
				animation: google.maps.Animation.BOUNCE,
			});
    		}
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
    }

	function clearFilter() {
		markerList.forEach(function(visibility){
			this.belowDistance(true)
		});
		setMarkers(filteredMarkers);
		//createListings(filteredMarkers);
	};

	//converts meters to miles, rounding to the tenth
	//called by filterByDistance()
	function metersToMiles(numberMeters){
		var toMileConversion = 0.000621371
		var miles = numberMeters * toMileConversion
		var miles = Math.round(miles * 10)/10
		return miles
	};

	function selectBike(){
		$('#speedSelector').empty();
		$('#speedSelector').append(bikeDiv)
	};

	function selectRun(){
		$('#speedSelector').empty();
		$('#speedSelector').append(runDiv)
	};

var map;

function initMap() {
	map = new google.maps.Map(document.getElementById('map'), {
	  center: {lat: 46.8772, lng: -96.7898},
	  zoom: 12
		});

	largeInfowindow = new google.maps.InfoWindow();

	var gymLocations = {
  	  location: map.center,
  	  radius: '20000',
   	  query: 'gym'
 	};

	service = new google.maps.places.PlacesService(map);
 	service.textSearch(gymLocations, gymMarkers);
};

